name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual triggering
    inputs:
      publish:
        description: 'Publish to PyPI'
        required: true
        default: false
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        
    - name: Install dependencies
      run: |
        poetry install
        pip install flake8 mypy pytest
      
    - name: Run linting
      run: flake8 tidystring/
      
    - name: Run type checking
      run: mypy tidystring/
      
    - name: Run tests
      run: pytest
      
    - name: Build package
      run: poetry build
      
    - name: Publish to PyPI
      if: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true') }}
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: poetry publish